### ISSUE TITLE
Adding files for albumArt and songs

### ISSUE THREAD

**Issue by AbhigyaShridhar** [giannicrivello/AudioShack_BE#1]
Right now, albumArt model has an image field, but it stores a string instead of a file. This should be changed. 

Song model should also include a file (mp3) 

These files should be stored in the static directory of the project. 

Reference: https://youtu.be/pPSZpCVRbvQ

The file name should be auto generated by the backend
Something like songName_audio.mp3     imageID_image.jpeg

**Comment by AbhigyaShridhar** [comment]
The models may use a string, but if so, that string should store file name, and there should be an api route to return that file

**Comment by giannicrivello** [comment]
Ok I think it is fixed. Let me know if I missed something.
